# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Iconos < Formula
  desc "CLI tool to generate icons and favicons from a source image"
  homepage "https://github.com/raucheacho/iconos"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/raucheacho/iconos/releases/download/v0.3.0/iconos_0.3.0_darwin_amd64.tar.gz"
      sha256 "c78fdb5af6fbe48fc499d07fe18ed0da6a3948d76ae10cf19b1e6ac52cc5f788"

      def install
        bin.install "iconos"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/raucheacho/iconos/releases/download/v0.3.0/iconos_0.3.0_darwin_arm64.tar.gz"
      sha256 "9a7c3b7f84fdb90c7a47dea08e56aea372b55d0292256f97cd7c8b63a3577881"

      def install
        bin.install "iconos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/raucheacho/iconos/releases/download/v0.3.0/iconos_0.3.0_linux_amd64.tar.gz"
      sha256 "3019a329aaf59b07f49a90d1630846583199371320777163eebbfef3212fdd67"
      def install
        bin.install "iconos"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/raucheacho/iconos/releases/download/v0.3.0/iconos_0.3.0_linux_arm64.tar.gz"
      sha256 "6d4df9130bf4dbffb2c801cad495463e2761df5b4ea8e53677085e90328525f3"
      def install
        bin.install "iconos"
      end
    end
  end

  test do
    system "#{bin}/iconos", "--help"
  end
end
