# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lanup < Formula
  desc "Automatically expose your local backend services on your local network"
  homepage "https://github.com/raucheacho/lanup"
  version "1.0.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/raucheacho/lanup/releases/download/v1.0.1/lanup_1.0.1_Darwin_x86_64.tar.gz"
      sha256 "eca6738b12c7b91997959d2cf0f58f25fe29d25cfdfeab151d34736251c9b03c"

      def install
        bin.install "lanup"
      end
    end
    on_arm do
      url "https://github.com/raucheacho/lanup/releases/download/v1.0.1/lanup_1.0.1_Darwin_arm64.tar.gz"
      sha256 "6ce53ba414050139c22d9b2a854f3a1b7d9f81ed767784530b1c7ca8d2aef282"

      def install
        bin.install "lanup"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/raucheacho/lanup/releases/download/v1.0.1/lanup_1.0.1_Linux_x86_64.tar.gz"
        sha256 "6b89b6e6aa26b9c8c1da9d86dc891c6e48ee8e9451c9fed26ed4d94a8a394d98"

        def install
          bin.install "lanup"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/raucheacho/lanup/releases/download/v1.0.1/lanup_1.0.1_Linux_arm64.tar.gz"
        sha256 "d86579bf30942f438df103bdaed20c6867e8557ce86c28eb4bd051cb1a4ea04d"

        def install
          bin.install "lanup"
        end
      end
    end
  end

  test do
    system "#{bin}/lanup --version"
  end
end
