# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lanup < Formula
  desc "Automatically expose your local backend services on your local network"
  homepage "https://github.com/raucheacho/lanup"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/raucheacho/lanup/releases/download/v1.0.0/lanup_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "44e458f4281263d3c3c38662717945372bc0f6dd8543bc3ec8a1d152a5b5f885"

      def install
        bin.install "lanup"
      end
    end
    on_arm do
      url "https://github.com/raucheacho/lanup/releases/download/v1.0.0/lanup_1.0.0_Darwin_arm64.tar.gz"
      sha256 "685656b8c6aa9b4126cd75ffd43dcf4298e83164c7bf7a3265f55b014a411df9"

      def install
        bin.install "lanup"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/raucheacho/lanup/releases/download/v1.0.0/lanup_1.0.0_Linux_x86_64.tar.gz"
        sha256 "47dcd9bb5fb072a08653efda3f4dee4de0e209566ef972543ea015ad8b3a3815"

        def install
          bin.install "lanup"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/raucheacho/lanup/releases/download/v1.0.0/lanup_1.0.0_Linux_arm64.tar.gz"
        sha256 "ca9cc72766591da00b764d95dcecb678cf962640dfaa92f5cb103a53b4a01a1e"

        def install
          bin.install "lanup"
        end
      end
    end
  end

  test do
    system "#{bin}/lanup --version"
  end
end
