# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rosia < Formula
  desc "Clean development dependencies and caches"
  homepage "https://github.com/raucheacho/rosia-cli"
  version "0.2.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/raucheacho/rosia-cli/releases/download/v0.2.3/rosia_0.2.3_darwin_amd64.tar.gz"
      sha256 "f25c091f00874c6561f208f3363a283052871556d01dbfaacb801416527ecbf6"

      def install
        bin.install "rosia"
      end
    end
    on_arm do
      url "https://github.com/raucheacho/rosia-cli/releases/download/v0.2.3/rosia_0.2.3_darwin_arm64.tar.gz"
      sha256 "2d47bc08f4ad062e2a8e570b60f22906f2ef25328f4c2cf44cefea0e963a5150"

      def install
        bin.install "rosia"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/raucheacho/rosia-cli/releases/download/v0.2.3/rosia_0.2.3_linux_amd64.tar.gz"
        sha256 "93b91c7c28f70e557c06e9b96aab46ab4599122aadc56e737a4cce4e11b93dfc"

        def install
          bin.install "rosia"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/raucheacho/rosia-cli/releases/download/v0.2.3/rosia_0.2.3_linux_arm64.tar.gz"
        sha256 "937f967c213aa532da85cdb15241ebc6fb1c771fee9e0ea583baaa58ffb15be4"

        def install
          bin.install "rosia"
        end
      end
    end
  end

  test do
    system "#{bin}/rosia", "version"
  end
end
