# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rosia < Formula
  desc "Clean development dependencies and caches"
  homepage "https://github.com/raucheacho/rosia-cli"
  version "0.2.4"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/raucheacho/rosia-cli/releases/download/v0.2.4/rosia_0.2.4_darwin_amd64.tar.gz"
      sha256 "7f9b7b8476d60577b8768bc1f3a353c4c40b86a0967f4fc977499242819a178d"

      def install
        bin.install "rosia"
      end
    end
    on_arm do
      url "https://github.com/raucheacho/rosia-cli/releases/download/v0.2.4/rosia_0.2.4_darwin_arm64.tar.gz"
      sha256 "7472898289a1e2f99878a7d2b9ea9a45d310bfbba3925952e54b58c7d644eff1"

      def install
        bin.install "rosia"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/raucheacho/rosia-cli/releases/download/v0.2.4/rosia_0.2.4_linux_amd64.tar.gz"
        sha256 "a2582cfe78ae3a3239fb0ce20d0bc0d1a91e8d95a877eb8e1ccc5e523ac0d2af"

        def install
          bin.install "rosia"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/raucheacho/rosia-cli/releases/download/v0.2.4/rosia_0.2.4_linux_arm64.tar.gz"
        sha256 "72283db3a8525361dbd351dccb0aa6fcc38a88ebb0183be976e0d8081b0b09dd"

        def install
          bin.install "rosia"
        end
      end
    end
  end

  test do
    system "#{bin}/rosia", "version"
  end
end
