# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rosia < Formula
  desc "Clean development dependencies and caches"
  homepage "https://github.com/raucheacho/rosia-cli"
  version "0.2.5"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/raucheacho/rosia-cli/releases/download/v0.2.5/rosia_0.2.5_darwin_amd64.tar.gz"
      sha256 "b5383e6b558976a1907a3c579cb3334fe420b60c9e23bbb00d9a47a0214e5d54"

      def install
        bin.install "rosia"
      end
    end
    on_arm do
      url "https://github.com/raucheacho/rosia-cli/releases/download/v0.2.5/rosia_0.2.5_darwin_arm64.tar.gz"
      sha256 "1c6ccdc60333fafef1332814a94f430f26954ec34d0507d87a6440e77e6ab13b"

      def install
        bin.install "rosia"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/raucheacho/rosia-cli/releases/download/v0.2.5/rosia_0.2.5_linux_amd64.tar.gz"
        sha256 "733d06e031ad02b2f1c774197b9869d5469fb8101c36229950875de43eaa6d52"

        def install
          bin.install "rosia"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/raucheacho/rosia-cli/releases/download/v0.2.5/rosia_0.2.5_linux_arm64.tar.gz"
        sha256 "f9709f89a5a4acb6142a4868f3c21964e1993ea00cf29db215aad4fcb81de473"

        def install
          bin.install "rosia"
        end
      end
    end
  end

  test do
    system "#{bin}/rosia", "version"
  end
end
