# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WotpCli < Formula
  desc "Self-hosted WhatsApp OTP provider CLI"
  homepage "https://github.com/raucheacho/wotp"
  version "1.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/raucheacho/wotp/releases/download/v1.0.5/wotp-cli_1.0.5_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "a726c50cb4911b9907b1e3a24200f368af395d6b3538df7109460ec8b70ef062"

      define_method(:install) do
        bin.install "wotp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/raucheacho/wotp/releases/download/v1.0.5/wotp-cli_1.0.5_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "088534670648c032d6851449ec072c98cf4a060fb75626b54175cd8b68c69f1c"

      define_method(:install) do
        bin.install "wotp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/raucheacho/wotp/releases/download/v1.0.5/wotp-cli_1.0.5_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "f8e37c084cca6f5f622402117b0e436dc92f7c11730dc5aa39c56dac94edc4c8"
      define_method(:install) do
        bin.install "wotp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/raucheacho/wotp/releases/download/v1.0.5/wotp-cli_1.0.5_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "777519cbcd3b1c230301f7aea27bbfea64a3c492ea418c0f81221045b0a31acf"
      define_method(:install) do
        bin.install "wotp"
      end
    end
  end

  test do
    system "#{bin}/wotp", "--help"
  end
end
