# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WotpCli < Formula
  desc "Self-hosted WhatsApp OTP provider CLI"
  homepage "https://github.com/raucheacho/wotp"
  version "1.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/raucheacho/wotp/releases/download/v1.5.1/wotp-cli_1.5.1_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "f7609cba0bb71a4de258f24b84057e50857a1510d2d50e02f57ae0f3f0da4a33"

      define_method(:install) do
        bin.install "wotp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/raucheacho/wotp/releases/download/v1.5.1/wotp-cli_1.5.1_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "f3da66df582d1495e357014fcd5ebedb63e34fdfc25dfb9edad0cdf9972f7050"

      define_method(:install) do
        bin.install "wotp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/raucheacho/wotp/releases/download/v1.5.1/wotp-cli_1.5.1_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "b520ec7bce4e95dc568b97ad3b94b72367aadf5086bd81822c6102db8b2dfbdc"
      define_method(:install) do
        bin.install "wotp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/raucheacho/wotp/releases/download/v1.5.1/wotp-cli_1.5.1_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "2aa189b5f1fd4a1f12e749cf4ce9223c0f4b800f98f62d5ad5feba287deed2ef"
      define_method(:install) do
        bin.install "wotp"
      end
    end
  end

  test do
    system "#{bin}/wotp", "--help"
  end
end
