# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WotpCli < Formula
  desc "Self-hosted WhatsApp OTP provider CLI"
  homepage "https://github.com/raucheacho/wotp"
  version "1.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/raucheacho/wotp/releases/download/v1.0.7/wotp-cli_1.0.7_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "83ee51d3029c4a848d3e07e932ac744d06188832598a60694753c2109b785b37"

      define_method(:install) do
        bin.install "wotp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/raucheacho/wotp/releases/download/v1.0.7/wotp-cli_1.0.7_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "8b0d9af14c79b09862f99a5d9606b5d7a5e04d602ad6824ef95b88abbd19aac5"

      define_method(:install) do
        bin.install "wotp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/raucheacho/wotp/releases/download/v1.0.7/wotp-cli_1.0.7_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "cdc80c5c97b18c61543a5b69839905237a85ab24414d71c5788226f2ebda3876"
      define_method(:install) do
        bin.install "wotp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/raucheacho/wotp/releases/download/v1.0.7/wotp-cli_1.0.7_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "e328b1cb0d025c3e69dc2015cdc212010155bbd1dad23c186d3617c3d56ba2a9"
      define_method(:install) do
        bin.install "wotp"
      end
    end
  end

  test do
    system "#{bin}/wotp", "--help"
  end
end
